<a href="https://colab.research.google.com/github/robinorex/Python-tutorial/blob/main/multiple_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
url="https://raw.githubusercontent.com/GrandmaCan/ML/main/Resgression/Salary_Data2.csv"
data=pd.read_csv(url)
data

YearsExperience EducationLevel City  Salary
0               3.0             大學  城市A    45.9
1               7.8           碩士以上  城市C    80.5
2               2.3           高中以下  城市A    25.2
3               5.1           高中以下  城市A    30.4
4              10.0           碩士以上  城市B    65.7
5               1.2           碩士以上  城市C    60.8
6               8.6             大學  城市C    50.1
7               6.9           碩士以上  城市A    70.3
8               4.2             大學  城市A    40.7
9               2.4           高中以下  城市A    28.1
10              5.3           高中以下  城市A    32.0
11              3.9             大學  城市A    48.3
12              7.2           碩士以上  城市C    84.2
13             10.0           碩士以上  城市B    70.9
14              1.5           碩士以上  城市C    62.4
15              8.4             大學  城市C    55.6
16              6.5           碩士以上  城市A    72.7
17              4.8             大學  城市A    42.9
18              2.1           高中以下  城市A    26.5
19              5.2           高中以下  城市A    31.6
20              3.5             大學  城市A    43.8
21              7.6           碩士以上  城市C    78.3
22             10.0           碩士以上  城市B    63.6
23              1.8           碩士以上  城市C    58.0
24              8.2             大學  城市C    48.3
25              6.3           碩士以上  城市A    68.4
26              4.6             大學  城市A    38.5
27              2.5           高中以下  城市A    24.9
28              5.0           高中以下  城市A    29.7
29              3.6             大學  城市A    41.6
30              7.4           碩士以上  城市C    76.9
31             10.0           碩士以上  城市B    60.2
32              1.7           碩士以上  城市C    56.3
33              8.0             大學  城市C    45.2
34              6.1           碩士以上  城市A    65.9
35              4.3             大學  城市A    36.7

In [ ]:
#Label encoding
data["EducationLevel"]=data["EducationLevel"].map({"高中以下":0, "大學":1, "碩士以上":2})
data

YearsExperience  EducationLevel City  Salary
0               3.0               1  城市A    45.9
1               7.8               2  城市C    80.5
2               2.3               0  城市A    25.2
3               5.1               0  城市A    30.4
4              10.0               2  城市B    65.7
5               1.2               2  城市C    60.8
6               8.6               1  城市C    50.1
7               6.9               2  城市A    70.3
8               4.2               1  城市A    40.7
9               2.4               0  城市A    28.1
10              5.3               0  城市A    32.0
11              3.9               1  城市A    48.3
12              7.2               2  城市C    84.2
13             10.0               2  城市B    70.9
14              1.5               2  城市C    62.4
15              8.4               1  城市C    55.6
16              6.5               2  城市A    72.7
17              4.8               1  城市A    42.9
18              2.1               0  城市A    26.5
19              5.2               0  城市A    31.6
20              3.5               1  城市A    43.8
21              7.6               2  城市C    78.3
22             10.0               2  城市B    63.6
23              1.8               2  城市C    58.0
24              8.2               1  城市C    48.3
25              6.3               2  城市A    68.4
26              4.6               1  城市A    38.5
27              2.5               0  城市A    24.9
28              5.0               0  城市A    29.7
29              3.6               1  城市A    41.6
30              7.4               2  城市C    76.9
31             10.0               2  城市B    60.2
32              1.7               2  城市C    56.3
33              8.0               1  城市C    45.2
34              6.1               2  城市A    65.9
35              4.3               1  城市A    36.7

In [ ]:
#將城市ABC轉換成三個特徵值
from sklearn.preprocessing import OneHotEncoder
onehot_encoder=OneHotEncoder()
onehot_encoder.fit(data[["City"]])   #要二維矩陣
city_encoded=onehot_encoder.transform(data[["City"]]).toarray()
city_encoded



array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [ ]:
data[["CityA","CityB","CityC"]]=city_encoded
data

YearsExperience  EducationLevel City  Salary  CityA  CityB  CityC
0               3.0               1  城市A    45.9    1.0    0.0    0.0
1               7.8               2  城市C    80.5    0.0    0.0    1.0
2               2.3               0  城市A    25.2    1.0    0.0    0.0
3               5.1               0  城市A    30.4    1.0    0.0    0.0
4              10.0               2  城市B    65.7    0.0    1.0    0.0
5               1.2               2  城市C    60.8    0.0    0.0    1.0
6               8.6               1  城市C    50.1    0.0    0.0    1.0
7               6.9               2  城市A    70.3    1.0    0.0    0.0
8               4.2               1  城市A    40.7    1.0    0.0    0.0
9               2.4               0  城市A    28.1    1.0    0.0    0.0
10              5.3               0  城市A    32.0    1.0    0.0    0.0
11              3.9               1  城市A    48.3    1.0    0.0    0.0
12              7.2               2  城市C    84.2    0.0    0.0    1.0
13             10.0               2  城市B    70.9    0.0    1.0    0.0
14              1.5               2  城市C    62.4    0.0    0.0    1.0
15              8.4               1  城市C    55.6    0.0    0.0    1.0
16              6.5               2  城市A    72.7    1.0    0.0    0.0
17              4.8               1  城市A    42.9    1.0    0.0    0.0
18              2.1               0  城市A    26.5    1.0    0.0    0.0
19              5.2               0  城市A    31.6    1.0    0.0    0.0
20              3.5               1  城市A    43.8    1.0    0.0    0.0
21              7.6               2  城市C    78.3    0.0    0.0    1.0
22             10.0               2  城市B    63.6    0.0    1.0    0.0
23              1.8               2  城市C    58.0    0.0    0.0    1.0
24              8.2               1  城市C    48.3    0.0    0.0    1.0
25              6.3               2  城市A    68.4    1.0    0.0    0.0
26              4.6               1  城市A    38.5    1.0    0.0    0.0
27              2.5               0  城市A    24.9    1.0    0.0    0.0
28              5.0               0  城市A    29.7    1.0    0.0    0.0
29              3.6               1  城市A    41.6    1.0    0.0    0.0
30              7.4               2  城市C    76.9    0.0    0.0    1.0
31             10.0               2  城市B    60.2    0.0    1.0    0.0
32              1.7               2  城市C    56.3    0.0    0.0    1.0
33              8.0               1  城市C    45.2    0.0    0.0    1.0
34              6.1               2  城市A    65.9    1.0    0.0    0.0
35              4.3               1  城市A    36.7    1.0    0.0    0.0

In [ ]:
data=data.drop(["City","CityC"],axis=1)  #刪掉column axis=1
data

YearsExperience  EducationLevel  Salary  CityA  CityB
0               3.0               1    45.9    1.0    0.0
1               7.8               2    80.5    0.0    0.0
2               2.3               0    25.2    1.0    0.0
3               5.1               0    30.4    1.0    0.0
4              10.0               2    65.7    0.0    1.0
5               1.2               2    60.8    0.0    0.0
6               8.6               1    50.1    0.0    0.0
7               6.9               2    70.3    1.0    0.0
8               4.2               1    40.7    1.0    0.0
9               2.4               0    28.1    1.0    0.0
10              5.3               0    32.0    1.0    0.0
11              3.9               1    48.3    1.0    0.0
12              7.2               2    84.2    0.0    0.0
13             10.0               2    70.9    0.0    1.0
14              1.5               2    62.4    0.0    0.0
15              8.4               1    55.6    0.0    0.0
16              6.5               2    72.7    1.0    0.0
17              4.8               1    42.9    1.0    0.0
18              2.1               0    26.5    1.0    0.0
19              5.2               0    31.6    1.0    0.0
20              3.5               1    43.8    1.0    0.0
21              7.6               2    78.3    0.0    0.0
22             10.0               2    63.6    0.0    1.0
23              1.8               2    58.0    0.0    0.0
24              8.2               1    48.3    0.0    0.0
25              6.3               2    68.4    1.0    0.0
26              4.6               1    38.5    1.0    0.0
27              2.5               0    24.9    1.0    0.0
28              5.0               0    29.7    1.0    0.0
29              3.6               1    41.6    1.0    0.0
30              7.4               2    76.9    0.0    0.0
31             10.0               2    60.2    0.0    1.0
32              1.7               2    56.3    0.0    0.0
33              8.0               1    45.2    0.0    0.0
34              6.1               2    65.9    1.0    0.0
35              4.3               1    36.7    1.0    0.0

In [ ]:
from sklearn.model_selection import train_test_split   #訓練集&測試集分開
x=data[["YearsExperience","EducationLevel","CityA","CityB"]]
y=data["Salary"]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=86)
x_train=x_train.to_numpy()
x_test=x_test.to_numpy()


array([[ 5.3,  0. ,  1. ,  0. ],
       [ 8.6,  1. ,  0. ,  0. ],
       [ 2.3,  0. ,  1. ,  0. ],
       [ 5.1,  0. ,  1. ,  0. ],
       [ 8.4,  1. ,  0. ,  0. ],
       [ 4.2,  1. ,  1. ,  0. ],
       [ 1.2,  2. ,  0. ,  0. ],
       [ 2.1,  0. ,  1. ,  0. ],
       [ 8. ,  1. ,  0. ,  0. ],
       [ 3. ,  1. ,  1. ,  0. ],
       [ 4.6,  1. ,  1. ,  0. ],
       [ 7.6,  2. ,  0. ,  0. ],
       [10. ,  2. ,  0. ,  1. ],
       [ 1.5,  2. ,  0. ,  0. ],
       [ 3.6,  1. ,  1. ,  0. ],
       [ 7.4,  2. ,  0. ,  0. ],
       [ 1.8,  2. ,  0. ,  0. ],
       [10. ,  2. ,  0. ,  1. ],
       [ 4.8,  1. ,  1. ,  0. ],
       [10. ,  2. ,  0. ,  1. ],
       [ 6.3,  2. ,  1. ,  0. ],
       [ 7.2,  2. ,  0. ,  0. ],
       [ 6.1,  2. ,  1. ,  0. ],
       [ 2.5,  0. ,  1. ,  0. ],
       [ 2.4,  0. ,  1. ,  0. ],
       [ 5. ,  0. ,  1. ,  0. ],
       [ 1.7,  2. ,  0. ,  0. ],
       [ 3.5,  1. ,  1. ,  0. ]])

In [ ]:
#特徵縮放 因為Years experience這欄位的數值顯著大於其他 因此要透過標準化(x-mean(x))/std(x)
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)
x_test


array([[ 5.20e+00, -2.48e-17,  1.00e+00,  5.95e-17],
       [ 4.30e+00,  1.00e+00,  1.00e+00,  5.95e-17],
       [ 6.50e+00,  2.00e+00,  1.00e+00,  5.95e-17],
       [ 1.00e+01,  2.00e+00,  0.00e+00,  1.00e+00],
       [ 6.90e+00,  2.00e+00,  1.00e+00,  5.95e-17],
       [ 8.20e+00,  1.00e+00,  0.00e+00,  5.95e-17],
       [ 3.90e+00,  1.00e+00,  1.00e+00,  5.95e-17],
       [ 7.80e+00,  2.00e+00,  0.00e+00,  5.95e-17]])

In [ ]:
import numpy as np
w=np.array([1,2,3,4])  #假設w1,w2,w3,w4
b=1
y_pred=(x_train*w).sum(axis=1)+b  #計算w1*x1+w2*x2+w3*x3+w4*x4...  sum(axis=1)代表row總和
#月薪y=w1*年資+w2*學歷+w3*cityA+w4*cityB+b


In [ ]:
((y_train-y_pred)**2).mean()   #設定cost function=(真實值-預測值)**2 作為評判標準
def compute_cost(x,y,w,b):
  y_pred=(x*w).sum(axis=1)+b
  cost=((y-y_pred)**2).mean()
  return cost
w=np.array([0,2,2,4])
b=1
compute_cost(x_train,y_train,w,b)

2689.8777398877965

In [ ]:
y_pred=(x_train*w).sum(axis=1)+b
b_gradient=(y_pred-y_train).mean()
w_gradient=np.zeros(x_train.shape[1])  #用shape來判斷欄位數 有w1,w2,w3,w4
for i in range(x_train.shape[1]):
  w_gradient[i]=(x_train[:,i]*(y_pred-y_train)).mean()
w_gradient,b_gradient
# w_gradient
# x_train.shape
# w1_gradient=(x_train[:,0]*(y_pred-y_train)).mean()     #cost function對w1微分,w1方向的斜率
# x1= x_train[:,0]
# w2_gradient=(x_train[:,1]*(y_pred-y_train)).mean()
# w3_gradient=(x_train[:,2]*(y_pred-y_train)).mean()
# w4_gradient=(x_train[:,3]*(y_pred-y_train)).mean()
# w1_gradient,w2_gradient,w3_gradient,w4_gradient

(array([ -6.18970101, -13.92146423,  11.34482789,  -1.32793132]),
 -49.324999999999996)

In [ ]:
def compute_gradient(x,y,w,b):
  y_pred=(x*w).sum(axis=1)+b
  w_gradient=np.zeros(x.shape[1])
  b_gradient=(y_pred-y).mean()
  for i in range(x.shape[1]):
    w_gradient[i]=(x[:,i]*(y_pred-y)).mean()
  return w_gradient, b_gradient   #計算出w,b的斜率

In [ ]:
w=np.array([0,2,2,4])
b=1
compute_gradient(x_train,y_train,w,b)

(array([-6.19e+00, -1.39e+01,  1.13e+01, -1.33e+00]), -49.324999999999996)

In [ ]:
w=np.array([1,2,2,4])
b=1
learning_rate=0.001
w_gradient,b_gradient=compute_gradient(x_train,y_train,w,b)
print(compute_cost(x_train,y_train,w,b))
w=w-w_gradient*learning_rate
b=b-b_gradient*learning_rate
w,b
print(compute_cost(x_train,y_train,w,b))

2678.49833787131
2672.972557100487


In [ ]:
np.set_printoptions(formatter={"float": "{: .2e}".format})
def gradient_descent(x,y,w_init,b_init,learning_rate,cost_function,gradient_function,run_iter,p_iter=1000):
  w=w_init
  b=b_init
  c_hist=[]
  w_hist=[]
  b_hist=[]
  for i in range(run_iter):
    w_gradient, b_gradient=gradient_function(x,y,w,b)
    w=w-w_gradient*learning_rate
    b=b-b_gradient*learning_rate
    cost=cost_function(x,y,w,b)
    w_hist.append(w)
    c_hist.append(cost)
    b_hist.append(b)
    if i%p_iter==0:
      print(f"Iteration{i:5}: Cost: {cost }, W: {w }, B: {b }, w_gradient: {w_gradient }, b_gradient: {b_gradient } ")
  return w,b,w_hist,b_hist,c_hist

In [ ]:
w_init=np.array([1,2,2,4])
b_init=0
learning_rate=1.0e-2
run_iter=20000

w_final,b_final,w_hist,b_hist,c_hist=gradient_descent(x_train,y_train,w_init,b_init,learning_rate,compute_cost,compute_gradient,run_iter,p_iter=1000)

Iteration    0: Cost: 2721.184622701739, W: [ 1.05e+00  2.14e+00  1.89e+00  4.01e+00], B: 0.50325, w_gradient: [-5.19e+00 -1.36e+01  1.09e+01 -7.20e-01], b_gradient: -50.324999999999996 
Iteration 1000: Cost: 21.40430092236068, W: [ 5.06e+00  1.44e+01 -1.56e+00 -3.39e+00], B: 50.322849132904324, w_gradient: [-6.49e-02 -7.49e-02 -8.08e-02  5.51e-02], b_gradient: -0.002172593025937911 
Iteration 2000: Cost: 21.34032847886188, W: [ 5.25e+00  1.46e+01 -1.29e+00 -3.55e+00], B: 50.32499990714439, w_gradient: [-2.61e-03 -4.21e-03 -4.57e-03  2.01e-03], b_gradient: -9.379355045017032e-08 
Iteration 3000: Cost: 21.34016249767344, W: [ 5.25e+00  1.46e+01 -1.28e+00 -3.56e+00], B: 50.32499999999599, w_gradient: [-1.22e-04 -2.25e-04 -2.44e-04  9.08e-05], b_gradient: -4.054661368562457e-12 
Iteration 4000: Cost: 21.340162050032642, W: [ 5.26e+00  1.46e+01 -1.28e+00 -3.56e+00], B: 50.324999999999655, w_gradient: [-6.16e-06 -1.18e-05 -1.28e-05  4.50e-06], b_gradient: -3.4677023157720605e-13 
Iteration 

In [ ]:
w_init=np.array([1,2,2,4])
b_init=0
learning_rate=1.0e-2
run_iter=20000

w_final,b_final,w_hist,b_hist,c_hist=gradient_descent(x_train,y_train,w_init,b_init,learning_rate,compute_cost,compute_gradient,run_iter,p_iter=1000)

Iteration    0: Cost: 2721.184622701739, W: [ 1.05e+00  2.14e+00  1.89e+00  4.01e+00], B: 0.50325, w_gradient: [-5.19e+00 -1.36e+01  1.09e+01 -7.20e-01], b_gradient: -50.324999999999996 
Iteration 1000: Cost: 21.40430092236068, W: [ 5.06e+00  1.44e+01 -1.56e+00 -3.39e+00], B: 50.322849132904324, w_gradient: [-6.49e-02 -7.49e-02 -8.08e-02  5.51e-02], b_gradient: -0.0021725930259385456 
Iteration 2000: Cost: 21.340328478861874, W: [ 5.25e+00  1.46e+01 -1.29e+00 -3.55e+00], B: 50.32499990714439, w_gradient: [-2.61e-03 -4.21e-03 -4.57e-03  2.01e-03], b_gradient: -9.37935495619919e-08 
Iteration 3000: Cost: 21.34016249767343, W: [ 5.25e+00  1.46e+01 -1.28e+00 -3.56e+00], B: 50.32499999999599, w_gradient: [-1.22e-04 -2.25e-04 -2.44e-04  9.08e-05], b_gradient: -4.055930194876315e-12 
Iteration 4000: Cost: 21.340162050032642, W: [ 5.26e+00  1.46e+01 -1.28e+00 -3.56e+00], B: 50.324999999999655, w_gradient: [-6.16e-06 -1.18e-05 -1.28e-05  4.50e-06], b_gradient: -3.461358184202774e-13 
Iteration 

In [ ]:
w_final,b_final

(array([ 5.26e+00,  1.46e+01, -1.28e+00, -3.56e+00]), 50.324999999999655)

In [ ]:
y_pred=(w_final*x_test).sum(axis=1)+b_final
pd.DataFrame({
    "y_pred":y_pred,
    "y_test":y_test
})   #測試集上的預測結果與測試集上的真實資料做比對


y_pred  y_test
19  29.012893    31.6
35  45.502882    36.7
16  67.887892    72.7
22  65.600000    63.6
7   68.648540    70.3
24  55.477621    48.3
11  44.742234    48.3
1   72.918419    80.5

In [ ]:
compute_cost(x_test,y_test,w_final,b_final)

29.45903497684948

In [ ]:
#年資5.3年 碩士 城市a  來預測他薪水Y
x_real=np.array([[5.3,2,1,0]])
x_real=scaler.transform(x_real)
y_real=(w_final*x_real).sum(axis=1)+b_final
y_real



array([ 6.56e+01])